version: "3.9"

services:

  nginx:
    image: nginx:1.25
    container_name: nginx_cache
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_cache:/var/cache/nginx

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"

  memcached:
    image: memcached:1.6
    container_name: memcached_cache
    ports:
      - "11211:11211"
  postgres:
    image: postgres:15
    container_name: pg_catalog
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c shared_buffers=1GB
      -c effective_cache_size=3GB
      -c work_mem=16MB
      -c max_connections=200
      -c log_min_duration_statement=200

volumes:
  pgdata:
  nginx_cache:


